apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: zauvs4oqd-go
  janus-idp.io/tekton: zauvs4oqd-go
  backstage.io/kubernetes-id: zauvs4oqd-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: zauvs4oqd-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
