apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: zauvs4oqd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: zauvs4oqd-go 
  name: zauvs4oqd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: zauvs4oqd-go 
